name: Config Update Trigger

on:
  push:
    branches: [ main, master ]
    paths:
      - 'config.json'
      - 'example_custom_rules.py'
      - 'CUSTOM_RULES.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-on-config-change:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run arXiv Bot with new config
      run: |
        echo "🔄 Configuration changed, updating papers..."
        python arxiv_bot.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "⚙️ Update papers with new configuration - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push
        
    - name: Show summary
      run: |
        echo "✅ Configuration update completed"
        echo "📊 Check README.md for updated papers" 