name: Simple arXiv Bot Update

on:
  push:
    branches: [ main, master ]
    paths:
      - 'config.json'
      - 'arxiv_bot.py'
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser flask requests
        
    - name: Run arXiv Bot
      run: |
        python arxiv_bot.py
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Update papers from arXiv - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 